In [1]:
import pandas as pd
import os

In [3]:
# csv read
kto2 = pd.read_csv('./output/kto2.csv')
kto2.head()

,국적,관광,상용,공용,유학/연수,기타,계,기준년월,대륙,관광객 비율(%),전체비율(%)
0,일본,198805,2233,127,785,4576,206526,2019-01,아시아,96.3,22.5
1,대만,86393,74,22,180,1285,87954,2019-01,아시아,98.2,9.8
2,홍콩,34653,59,2,90,1092,35896,2019-01,아시아,96.5,3.9
3,마카오,2506,2,0,17,45,2570,2019-01,아시아,97.5,0.3
4,태국,34004,37,199,96,6998,41334,2019-01,아시아,82.3,3.8

In [4]:
# 마지막 5개의 행 출력
kto2.tail()

,국적,관광,상용,공용,유학/연수,기타,계,기준년월,대륙,관광객 비율(%),전체비율(%)
55,대양주 기타,555,3,4,0,52,614,2019-01,오세아니아,90.4,0.1
56,남아프리카공화국,368,9,1,6,616,1000,2019-01,아프리카,36.8,0.0
57,아프리카 기타,768,718,90,206,908,2690,2019-01,아프리카,28.6,0.1
58,국적미상,33,4,0,1,16,54,2019-01,기타대륙,61.1,0.0
59,교포,0,0,0,0,15526,15526,2019-01,교포,0.0,0.0

In [ ]:
# 1년은 12개월의 구조를 가지고 있고, 해가 변경될 때마다 월이 반복되므로
# 함수로 제작할 필요가 있음
# 2010년 1월부터 2020년 3월까지의 데이터 통합

In [12]:
# 날짜를 기준으로 통합을 진행함.
# 2019-01, 자리수가 일치하지 않는 문제 발생(2 -> 02로 변경, ''.zfill(n) 사용)
for yy in range(2010, 2021): # 2010~2020
    for mm in range(1, 13): # 01~12
        yymm = '{0}-{1}'.format(yy, str(mm).zfill(2))
        print(yymm, '', end='')

2010-01 2010-02 2010-03 2010-04 2010-05 2010-06 2010-07 2010-08 2010-09 2010-10 2010-11 2010-12 2011-01 2011-02 2011-03 2011-04 2011-05 2011-06 2011-07 2011-08 2011-09 2011-10 2011-11 2011-12 2012-01 2012-02 2012-03 2012-04 2012-05 2012-06 2012-07 2012-08 2012-09 2012-10 2012-11 2012-12 2013-01 2013-02 2013-03 2013-04 2013-05 2013-06 2013-07 2013-08 2013-09 2013-10 2013-11 2013-12 2014-01 2014-02 2014-03 2014-04 2014-05 2014-06 2014-07 2014-08 2014-09 2014-10 2014-11 2014-12 2015-01 2015-02 2015-03 2015-04 2015-05 2015-06 2015-07 2015-08 2015-09 2015-10 2015-11 2015-12 2016-01 2016-02 2016-03 2016-04 2016-05 2016-06 2016-07 2016-08 2016-09 2016-10 2016-11 2016-12 2017-01 2017-02 2017-03 2017-04 2017-05 2017-06 2017-07 2017-08 2017-09 2017-10 2017-11 2017-12 2018-01 2018-02 2018-03 2018-04 2018-05 2018-06 2018-07 2018-08 2018-09 2018-10 2018-11 2018-12 2019-01 2019-02 2019-03 2019-04 2019-05 2019-06 2019-07 2019-08 2019-09 2019-10 2019-11 2019-12 2020-01 2020-02 2020-03 2020-04 2020-05 2020-06 2020-07 2020-08 2020-09 2020-10 2020-11 2020-12

In [30]:
# 하나의 국가명을 전달 받아 대륙명을 리턴하는 함수
def getContinent(nation_name):
    continents = ''
    
    if "'일본', '대만', '홍콩', '마카오', '태국', \
        '말레이시아', '필리핀', '인도네시아',\
        '싱가포르', '미얀마', '베트남', '인도',\
        '스리랑카', '파키스탄', '방글라데시',\
        '캄보디아', '몽골', '중국', '이란', \
        '이스라엘', '터키', '우즈베키스탄', \
        '카자흐스탄', 'GCC', '아시아 기타'".find(nation_name) >= 0: 
        continents='아시아'
    elif "'미국', '캐나다', '멕시코', '브라질', \
         '미주 기타'".find(nation_name) >= 0: 
        continents='아메리카'
    elif "'영국', '독일', '프랑스', '네덜란드','스웨덴', '스위스', \
          '이탈리아', '덴마크', '노르웨이', '벨기에', '오스트리아',\
          '스페인', '그리스', '포르투갈', '핀란드', '아일랜드',\
          '우크라이나', '러시아', '크로아티아', '루마니아',\
          '불가리아', '폴란드', '구주 기타'".find(nation_name) >= 0:
        continents='유럽'
    elif "'오스트레일리아', '뉴질랜드', '대양주 기타'".find(nation_name) >= 0:
        continents='오세아니아'         
    elif "'남아프리카공화국', '아프리카 기타'".find(nation_name) >= 0:
        continents='아프리카'
    elif "'국적미상'".find(nation_name) >= 0:
        continents='기타대륙'         
    elif "'교포'".find(nation_name) >= 0:
        continents='교포'
    else:
        print(nation_name + ' 발견 안됨')
        
    return continents

In [31]:
getContinent('중국')

'아시아'

In [48]:
def getContinents(df):
    continents = [] # 대륙명 저장
    for i in range(len(df)):
        nation_name = df.loc[i][0]
        # print(nation_name) # 국가명
        if "'일본', '대만', '홍콩', '마카오', '태국', \
            '말레이시아', '필리핀', '인도네시아',\
            '싱가포르', '미얀마', '베트남', '인도',\
            '스리랑카', '파키스탄', '방글라데시',\
            '캄보디아', '몽골', '중국', '이란', \
            '이스라엘', '터키', '우즈베키스탄', \
            '카자흐스탄', 'GCC', '아시아 기타'".find(nation_name) >= 0: 
            continents.append('아시아')
        elif "'미국', '캐나다', '멕시코', '브라질', \
             '미주 기타'".find(nation_name) >= 0: 
            continents.append('아메리카') 
        elif "'영국', '독일', '프랑스', '네덜란드','스웨덴', '스위스', \
              '이탈리아', '덴마크', '노르웨이', '벨기에', '오스트리아',\
              '스페인', '그리스', '포르투갈', '핀란드', '아일랜드',\
              '우크라이나', '러시아', '크로아티아', '루마니아',\
              '불가리아', '폴란드', '구주 기타'".find(nation_name) >= 0:
            continents.append('유럽') 
        elif "'오스트레일리아', '뉴질랜드', '대양주 기타'".find(nation_name) >= 0:
            continents.append('오세아니아')         
        elif "'남아프리카공화국', '아프리카 기타'".find(nation_name) >= 0:
            continents.append('아프리카')  
        elif "'국적미상'".find(nation_name) >= 0:
            continents.append('기타대륙')          
        elif "'교포'".find(nation_name) >= 0:
            continents.append('교포')
    return continents
# getContinents(df)

In [58]:
# 년월을 입력 받아 DataFrame을 리턴하는 함수
def create_data(yy, mm):
    df = pd.DataFrame() # return 할 객체
    mm = str(mm).zfill(2) # 1 -> 01
    file_path = './data/kto_{0}{1}.xlsx'.format(yy, mm)
    if os.path.exists(file_path):
        df = pd.read_excel(file_path, header=1, skipfooter=4, usecols='A:G')
        
        # 기준년월 칼럼 추가
        df['기준년월'] = '{0}-{1}'.format(yy, mm)
        
        # 순수 국가명만 추출
        continents = ['아시아주', '미주', '구주', '대양주', \
                      '아프리카주', '기타대륙', '교포소계']
        df = df[df.국적.isin(continents) == False]
        df = df.reset_index(drop=True) # 다시 인덱스를 0부터 설정
        
        # 대륙 칼럼 추가
        df['대륙'] = getContinents(df)
        
        # 관광객 비율(%)
        df['관광객 비율(%)'] = round(df['관광']/df['계']*100, 1)
        
        # 관광 / 전체 관광객 * 100 = 전체비율(%)
        tour_sum= sum(df['관광'])
        df['전체비율(%)'] = round(df['관광']/tour_sum*100, 1)
    return df

In [59]:
df = create_data(2020, 3)
df

,국적,관광,상용,공용,유학/연수,기타,계,기준년월,대륙,관광객 비율(%),전체비율(%)
0,일본,6478,282,16,868,703,8347,2020-03,아시아,77.6,20.6
1,대만,274,6,1,125,179,585,2020-03,아시아,46.8,0.9
2,홍콩,173,4,0,51,34,262,2020-03,아시아,66.0,0.5
3,마카오,11,1,0,4,0,16,2020-03,아시아,68.8,0.0
4,태국,1059,21,11,124,1156,2371,2020-03,아시아,44.7,3.4
5,말레이시아,289,4,1,102,494,890,2020-03,아시아,32.5,0.9
6,필리핀,2048,13,33,67,2378,4539,2020-03,아시아,45.1,6.5
7,인도네시아,1030,6,7,373,2344,3760,2020-03,아시아,27.4,3.3
8,싱가포르,159,5,6,13,36,219,2020-03,아시아,72.6,0.5
9,미얀마,741,0,0,109,1669,2519,2020-03,아시아,29.4,2.4
10,베트남,941,15,5,2200,887,4048,2020-03,아시아,23.2,3.0
11,인도,555,42,5,92,893,1587,2020-03,아시아,35.0,1.8
12,스리랑카,20,1,0,19,401,441,2020-03,아시아,4.5,0.1
13,파키스탄,70,44,5,138,217,474,2020-03,아시아,14.8,0.2
14,방글라데시,77,8,1,133,347,566,2020-03,아시아,13.6,0.2
15,캄보디아,45,10,6,35,1087,1183,2020-03,아시아,3.8,0.1
16,몽골,191,5,9,357,112,674,2020-03,아시아,28.3,0.6
17,중국,5040,115,2,7388,4050,16595,2020-03,아시아,30.4,16.0
18,이란,9,1,1,12,11,34,2020-03,아시아,26.5,0.0
19,이스라엘,61,2,0,3,2,68,2020-03,아시아,89.7,0.2
20,터키,114,2,0,21,105,242,2020-03,아시아,47.1,0.4
21,우즈베키스탄,89,19,0,260,414,782,2020-03,아시아,11.4,0.3
22,카자흐스탄,144,4,1,95,323,567,2020-03,아시아,25.4,0.5
23,GCC,26,5,1,19,26,77,2020-03,아시아,33.8,0.1
24,아시아 기타,75,79,14,500,893,1561,2020-03,아시아,4.8,0.2
25,미국,3995,47,598,79,5851,10570,2020-03,아메리카,37.8,12.7
26,캐나다,1022,3,9,21,1350,2405,2020-03,아메리카,42.5,3.2
27,멕시코,150,1,2,26,209,388,2020-03,아메리카,38.7,0.5
28,브라질,107,3,4,18,159,291,2020-03,아메리카,36.8,0.3
29,미주 기타,239,3,8,46,160,456,2020-03,아메리카,52.4,0.8
30,영국,550,26,9,44,544,1173,2020-03,유럽,46.9,1.7
31,독일,611,41,8,121,414,1195,2020-03,유럽,51.1,1.9
32,프랑스,528,62,19,184,424,1217,2020-03,유럽,43.4,1.7
33,네덜란드,156,5,0,29,407,597,2020-03,유럽,26.1,0.5
34,스웨덴,115,4,1,38,30,188,2020-03,유럽,61.2,0.4
35,스위스,60,4,0,14,27,105,2020-03,유럽,57.1,0.2
36,이탈리아,73,13,2,18,142,248,2020-03,유럽,29.4,0.2
37,덴마크,91,0,2,10,11,114,2020-03,유럽,79.8,0.3
38,노르웨이,53,4,1,19,20,97,2020-03,유럽,54.6,0.2
39,벨기에,62,6,2,8,86,164,2020-03,유럽,37.8,0.2
40,오스트리아,35,3,0,5,53,96,2020-03,유럽,36.5,0.1
41,스페인,127,6,5,26,91,255,2020-03,유럽,49.8,0.4
42,그리스,129,4,2,5,59,199,2020-03,유럽,64.8,0.4
43,포르투갈,23,1,0,1,36,61,2020-03,유럽,37.7,0.1
44,핀란드,30,0,1,14,99,144,2020-03,유럽,20.8,0.1
45,아일랜드,29,5,0,1,71,106,2020-03,유럽,27.4,0.1
46,우크라이나,214,30,2,7,377,630,2020-03,유럽,34.0,0.7
47,러시아,2189,42,4,115,2950,5300,2020-03,유럽,41.3,6.9
48,크로아티아,65,2,0,2,15,84,2020-03,유럽,77.4,0.2
49,루마니아,86,3,2,6,76,173,2020-03,유럽,49.7,0.3
50,불가리아,40,0,0,8,32,80,2020-03,유럽,50.0,0.1
51,폴란드,134,12,0,12,164,322,2020-03,유럽,41.6,0.4
52,구주 기타,257,1,3,63,214,538,2020-03,유럽,47.8,0.8
53,오스트레일리아,363,15,3,12,367,760,2020-03,오세아니아,47.8,1.2
54,뉴질랜드,90,3,4,4,174,275,2020-03,오세아니아,32.7,0.3
55,대양주 기타,16,0,2,0,32,50,2020-03,오세아니아,32.0,0.1
56,남아프리카공화국,29,0,0,0,208,237,2020-03,아프리카,12.2,0.1
57,아프리카 기타,103,134,6,145,558,946,2020-03,아프리카,10.9,0.3
58,국적미상,7,0,0,0,4,11,2020-03,기타대륙,63.6,0.0
59,교포,0,0,0,0,1615,1615,2020-03,교포,0.0,0.0

In [73]:
kto = pd.DataFrame()
for yy in range(2010, 2021): # 2010~2020
    for mm in range(1, 13): # 01~12
        rdf = create_data(yy, mm)
        kto = kto.append(rdf, ignore_index=True) # 원본 인덱스를 유지하지 않고, 계속 증가시킴

In [74]:
kto

,국적,관광,상용,공용,유학/연수,기타,계,기준년월,대륙,관광객 비율(%),전체비율(%)
0,일본,202825,1750,89,549,3971,209184,2010-01,아시아,97.0,50.6
1,대만,35788,41,17,37,516,36399,2010-01,아시아,98.3,8.9
2,홍콩,13874,55,0,21,595,14545,2010-01,아시아,95.4,3.5
3,마카오,554,0,0,0,0,554,2010-01,아시아,100.0,0.1
4,태국,13374,39,13,53,4335,17814,2010-01,아시아,75.1,3.3
...,...,...,...,...,...,...,...,...,...,...,...
7375,대양주 기타,16,0,2,0,32,50,2020-03,오세아니아,32.0,0.1
7376,남아프리카공화국,29,0,0,0,208,237,2020-03,아프리카,12.2,0.1
7377,아프리카 기타,103,134,6,145,558,946,2020-03,아프리카,10.9,0.3
7378,국적미상,7,0,0,0,4,11,2020-03,기타대륙,63.6,0.0
7379,교포,0,0,0,0,1615,1615,2020-03,교포,0.0,0.0

In [ ]:
kto.to_csv('')